### ISSUE TITLE
FIGMA - Start basic design architecture

### ISSUE THREAD

**Issue by lucashlz** [witch-puzzles/backend-puzzles#2]
**Description**

I will start by creating a basic architecture on the FIGMA project.

Link to the figma : https://www.figma.com/design/klAuhxfzReRrDQxlgsVj95/Witch---Web?node-id=0-1&t=fsUGHwMWFQ3D1jMS-1

**Comment by erthium** [comment]
Can you change the access to `anyone with the link` ?

**Comment by Utkub24** [comment]
Maybe we can move this to https://github.com/witch-puzzles/frontend-puzzles ?

**Comment by lucashlz** [comment]
moved to frontend
